### ISSUE TITLE
cmsis-dap  does not appear in windowns 10 once that is programmed with the current firware

### ISSUE THREAD

**Issue by marcel41** [L-Tek/DAPLINK#3]
Hello, I have been trying to find help with cmsis-dap Non-standard 7pin, I would like to know if it is normal that the device does not appear in windows 10 once that you have programmed the cmsis-dap. The reason for asking this  is because I am currently trying to attach a zybo70-10 with the cmsis-dap to debug a program which I haven't been successful to do.

**Comment by gorazdko** [comment]
> once that you have programmed the cmsis-dap.

i assume you have successfully completed the [tutorial](https://github.com/L-Tek/DAPLINK/blob/master/docs/cmsis-dap.md)

> the device does not appear in windows 10

* the device and its serial number should be seen in keil uvision as in the [picture](https://raw.githubusercontent.com/L-Tek/DAPLINK/master/docs/img/cmsis-dap/jtag.png), 
* alternatively you should be able to see this info from device manager -> usb ports/controllers
* if you are thinking of the disk drive, it wont appear, which is the correct behaviour.

> I am currently trying to attach a zybo70-10 with the cmsis-dap

double check the wiring

**Comment by marcel41** [comment]
hello, thank you for your reply, I do not use keil uvision to debug my board, I use ds-5 with a prebuilt plataform to debug but I am still able to see the serial number,  I am sure that I am connecting cmsis-dap into the correct pmod from the zybo but I getting an error when debugging.

**Comment by gorazdko** [comment]
> I getting an error when debugging

but you're able to flash your firmware onto the mcu of zybo successfully? What is the error?

This should be your pmod, right? 
![image](https://user-images.githubusercontent.com/25270775/64377665-369de780-d02b-11e9-9a09-c20379678cda.png)


Unfortunately, im not familiar with your debugging platform, neither much with this mcu from this perspective. One thing i could suggest regarding the correct wiring: if your wiring is correct you will see the IDCODE and device name as in the [picture](https://raw.githubusercontent.com/L-Tek/DAPLINK/master/docs/img/cmsis-dap/jtag.png). For this you install keil uvision 5, no license is needed for this.

Another thing is opening an issue to the repo of your debugging platform and see if they can help.

**Comment by marcel41** [comment]
thank you for all your help, I will try this tomorrow.

**Comment by cstrahan** [comment]
On Linux, the cmsis-dap doesn't show up under `lsusb`. I've flashed the firmware per the instructions, but am still not having any luck. Any suggestions?
